version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql:8.0.3
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data: {}
